### ISSUE TITLE
Support piped input for encode/decode commands

### ISSUE THREAD

**Issue by shekhirin** [gakonst/dapptools-rs#143]
```bash
➜  dapptools-rs git:(master) ✗ cargo run --bin seth -- --to-ascii 0x547572626f44617070546f6f6c73
    Finished dev [unoptimized + debuginfo] target(s) in 0.46s
     Running `target/debug/seth --to-ascii 0x547572626f44617070546f6f6c73`
TurboDappTools

➜  dapptools-rs git:(master) ✗ echo '0x547572626f44617070546f6f6c73' | cargo run --bin seth -- --to-ascii
    Finished dev [unoptimized + debuginfo] target(s) in 0.30s
     Running `target/debug/seth --to-ascii`
error: The following required arguments were not provided:
    <hexdata>

USAGE:
    seth --to-ascii <hexdata>

For more information try --help
```

---

Currently these commands need to be able to accept piped input:
  - [ ] `--from-ascii`
  - [ ] `--to-checksum-address`
  - [ ] `--to-ascii`
  - [ ] `--to-bytes32`
  - [ ] `--to-dec`
  - [x] `--to-fix`
  - [x] `--to-hex`
  - [ ] `--to-hexdata`
  - [ ] `--to-uint256`
  - [x] `--to-wei`

**Comment by gakonst** [comment]
Don't they already? That's why we have [this](https://github.com/gakonst/dapptools-rs/blob/master/dapptools/src/seth.rs#L174) method in certain commands

**Comment by shekhirin** [comment]
Yep, part of them already does it. Checked in TODO those who already support it. WDYT about others?
