### ISSUE TITLE
Add random fuzzing of inputs

### ISSUE THREAD

**Issue by gakonst** [gakonst/dapptools-rs#16]
ideally abstract over the backend so we can use both of the below:
https://github.com/AltSysrq/proptest
https://github.com/BurntSushi/quickcheck

instead using just the function selector as calldata, detect if the function has args and generate random inputs for N iterations 
https://github.com/gakonst/dapptools-rs/blob/master/dapp/src/runner.rs#L104

**Comment by transmissions11** [comment]
should take some pointers from the echidna fuzzing engine which keeps a malicious input db and has what they call "constant mining" (recycles state vars and return data as input)

**Comment by transmissions11** [comment]
oh and shrinking would be rly helpful too

**Comment by gakonst** [comment]
I think PropTest already has shrinking https://github.com/AltSysrq/proptest/search?q=shrink, as implemented in #44

**Comment by transmissions11** [comment]
Can we keep open for adding advanced features like mutation or constant mining? Or should I crate a new issue

**Comment by gakonst** [comment]
Yeah let's get more specific issues open for that, along with tags.
