### ISSUE TITLE
dapp build creates non-deterministic json structure

### ISSUE THREAD

**Issue by OdysLam** [gakonst/dapptools-rs#36]
Running the same `dapp build` will create different json files that are structurally the same, but are serialized in a different order. The order is reversed at random intervals.

For example, one invocation may create a `json` file that defines ContractA and then ContractB, while the next invocation may create a `json` file that defines ContractB and then ContractA. 

While the json are interchangeable, they are not identical and they can't be compared as strings. 

This was discovered when setting up tests for brew, which tested the output of `dapp build`.

![Screenshot 2021-09-22 at 3 01 15 PM](https://user-images.githubusercontent.com/13405632/134340919-00c32f1b-3b1d-4458-bcd5-884534ff0bc0.png)
.

**Comment by gakonst** [comment]
Can we not avoid having to test the output of `dapp build` in brew? I don't think we can easily solve this because json is an unordered data format?

**Comment by OdysLam** [comment]
I solved it by testing it with `jd` instead if comparing the strings. I opened the issue as an FYI

**Comment by gakonst** [comment]
Word, given that this is not a blocker, closing.
